---
- name: Check Demo
  hosts: localhost
  gather_facts: false
  tasks:
      - name: Cd to the directory
        set_fact:  
          sudo: "{{lookup('env','sudo_password')}}"
      - name: Execute command with sudo
        command: |
          "bin/bash -c 'echo "{{sudo}}" | sudo -S ls /root'"
        register: output

      - name: Display
        debug:
          msg: "{{output.stdout}}"
        
