---
- name: Check Demo
  hosts: localhost
  gather_facts: false
  tasks:
      - name: Cd to the directory
        set_fact:  
          sudo: "{{lookup('env','sudo_password')}}"
      - name: Execute command with sudo
        ansible.builtin.shell: |
          echo "{{sudo}}" | sudo -S ls /root
        args:
          exectuable: /bin/bash
        register: output

      - name: Display
        debug:
          msg: "{{output.stdout}}"
        
