---
- name: Check Demo
  hosts: localhost
  vars:
    secure: {{lookup('env','sudo_password')}}
  tasks:
      - name: Cd to the directory
        shell: | 
          {{secure}}
        register: output
      - name: Display
        debug:
          msg: "{{output.stdout}}"
        
