---
- name: Check Responses Value
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Execute command with sudo using expect
      command: whoami
      register: output

    - name: Display entire output details
      debug:
        var: output
