---
- name: Check Demo
  hosts: localhost
  tasks:
      - name: Cd to the directory
        command: echo {{lookup('env','reponame')}}
        register: output
      - name: Display
        debug:
          msg: {{output.results}}
        
