---
- name: Check Demo
  hosts: localhost
  gather_facts: false
  tasks:
      - name: Cd to the directory
        set_fact:  
          sudo: "{{lookup('env','sudo_password')}}"
      - name: Execute command with sudo
        expect:
          command: sudo ls /root
          responses:
            'Password:.*': "{{ sudo }}"
        register: output

      - name: Display
        debug:
          msg: "{{output.stdout}}"
        
