---
- name: Check Demo
  hosts: localhost
  tasks:
      - name: Cd to the directory
        command: | 
            echo '{{lookup('env','sudo_password')}}' | sudo -S systemctl restart nginx
        register: output
      - name: Display
        debug:
          msg: "{{output.stdout}}"
        
