---
- name: Check Demo
  hosts: localhost
  tasks:
      - name: Cd to the directory
        command: |
            cd /home/sutharsan/workspace/{{lookup('env','sudo_password')}}
        register: output
      - name: Display
        debug:
          msg: "{{output.stdout}}"
        
