---
- name: Check Responses Value
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display expected responses value
      debug:
        msg: "Expected response pattern: '{{ lookup('env', 'sudo_password') }}'"

    - name: Execute command with sudo using expect
      expect:
        command: sudo -S l
        responses:
          '.*[pP]assword.*': "{{ lookup('env', 'sudo_password') }}"
      register: output

    - name: Display entire output details
      debug:
        var: output
