---
- name: Check Demo
  hosts: localhost
  tasks:
      - name: Cd to the directory
        command: |
             sudo apt install yum | echo "{{lookup('env','reponame')}}"
        register: output
      - name: Display
        debug:
          msg: "{{output.stdout}}"
        
