---
- name: Check Demo
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Execute command with sudo using expect
      expect:
        command: sudo ls /root
        responses:
          '.password*': "{{ lookup('env', 'sudo_password') }}"
      register: output

    - name: Display output
      debug:
        msg: "{{ output.stdout }}"
