---
- name: Check Demo
  hosts: localhost
  tasks:
      - name: Cd to the directory
        command: |
            echo "{{sudo_password}}" | sudo nginx -t && 
            echo "{{sudo_password}}" | sudo systemctl restart nginx && 
            echo "{{sudo_password}}" | sudo systemctl reload nginx
        register: output
      - name: Display
        debug:
          msg: "{{output.stdout}}"
        
