---
- name: Check Demo
  hosts: localhost
  vars:
    secure: "{{lookup('env','sudo_password')}}"
  tasks:
      #- name: Cd to the directory
      #  shell: | 
       #   echo {{secure}}
        #register: output
      - name: Display
        debug:
          msg: "{{secure}}"
          unmasked: true
        
