---
- name: Check Demo
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Execute command with sudo
      command: sudo -S ls /root
      args:
        stdin: "{{ lookup('env', 'sudo_password') }}""
      register: output
      
    - name: Display
      debug:
        msg: "{{ output.stdout }}"

