---
- name: Check Demo
  hosts: localhost
  tasks:
      - name: Cd to the directory
        set_fact:  
          sudo: "{{lookup('env','sudo_password')}}"
        #register: output
      - name: Display
        debug:
          var: sudo
        
