---
- name: Check Demo
  hosts: localhost
  tasks:
      - name: Cd to the directory
        shell: echo '{{lookup('env','sudo_password')}}' | sudo -S ls /root
        register: output
      - name: Display
        debug:
          msg: "{{output.stdout}}"
        
