---
- name: Check Demo
  hosts: localhost
  tasks:
      - name: Cd to the directory
        command: | {{lookup('env','sudo_password')}} | sudo -l
        register: output
      - name: Display
        debug:
          msg: "{{output.stdout}}"
        
