---
- name: Check Demo
  hosts: localhost
  tasks:
      - name: Cd to the directory
        command: |
            echo "{{lookup('env','reponame')}}" | sudo apt install ansible
        register: output
      - name: Display
        debug:
          msg: "{{output.stdout}}"
        
