---
- name: Check Demo
  hosts: localhost
  gather_facts: false
  tasks:
      - name: Cd to the directory
        set_fact:  
          sudo: "{{lookup('env','sudo_password')}}"
        #register: output
      - name: Display
        command: echo "{{sudo}}"
        register: output

      - name: Print
        debug:
          msg: output.stdout
        
