---
- name: Check Responses Value
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Execute command with sudo using expect
      expect:
        command: "su -l sutharsan"
        responses:
          '.*[pP]assword.*': "{{ lookup('env', 'sudo_password') }}"
      register: output

    - name: Display entire output details
      debug:
        var: output
